# Generated by Django 5.2.8 on 2025-11-26 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('cursos', '0002_tutoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_examen', models.DateTimeField()),
                ('visible_estudiantes', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_examen', to='cursos.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_examen_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_examen'],
                'indexes': [models.Index(fields=['curso', 'fecha_examen'], name='calificacio_curso_i_f8fba0_idx')],
            },
        ),
    ]
